#!/bin/bash

# Check Java version
version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}')
if [[ "11.0" != "`echo -e "11.0\n$version" | sort -V | head -n1`" ]]; then
    echo "[ERROR] Java runtime version 11 or higher is required to use jshell."
    exit 1
fi

# Process input arguments
while [[ "$#" -gt 0 ]]; do
  case $1 in
    -k|--keystore) KEYSTORE="$2"; shift ;;
    *) OTHER_PARAMS="$OTHER_PARAMS $1"
  esac
  shift
done

# Prompt for missing information
if [ -z "$KEYSTORE" ]
then
  read -p "Keystore file name: " KEYSTORE
fi

# Create the keystore
echo [INFO] Creating keystore: $KEYSTORE
export KEYSTORE
jshell - <<END
  import java.io.*;
  import java.security.KeyStore;
  var keystore_name = System.getenv().get("KEYSTORE")
  var keystore = KeyStore.getInstance("PKCS12");
  keystore.load(null, null);
  var out = new FileOutputStream(keystore_name);
  keystore.store(out, new char[0]);
END

# Initialize the keystore
echo [INFO] Initializing keystore: $KEYSTORE
echo "" | keytool -importpass -alias AuthorizationToken -keystore $KEYSTORE -storepass ""

# Check result
keytool -list -keystore $KEYSTORE -storepass ""

exit